/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;


import Entity.Client_Numéros;
import Entity.Reservation;
import Entity.Voiture_Programme;
import static Tools.Tools.Message;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Abdelatif Hamdi
 */
public class Programme extends javax.swing.JFrame {

    /**
     * Creates new form frmProjet
     */
    public Programme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupPro = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Textduree = new controls.JTextBox(20);
        TextId = new controls.JTextBox(20);
        Textdestination = new controls.JTextBox(20);
        TextRecherche = new controls.JTextBox(20);
        jLabel6 = new javax.swing.JLabel();
        RadBtnNum = new javax.swing.JRadioButton();
        RadBtnDestination = new javax.swing.JRadioButton();
        RadBtnDurée = new javax.swing.JRadioButton();
        btnRecherche = new controls.JMyBottom();
        RdoDate = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPro = new javax.swing.JTable();
        btnRetoure = new controls.JMyBottom();
        btnTrouver = new controls.JMyBottom();
        btnTout = new controls.JMyBottom();
        btnEffacer = new controls.JMyBottom();
        btnSupprimer = new controls.JMyBottom();
        btnModifier = new controls.JMyBottom();
        btnAjouter = new controls.JMyBottom();
        jLabel7 = new javax.swing.JLabel();
        TextDate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        TextPrix = new controls.JTextBox(20);
        RdoPrix = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        TextMatricule = new controls.JTextBox(12);
        btnAjouter1 = new controls.JMyBottom();
        jLabel12 = new javax.swing.JLabel();
        TextnbrPers = new controls.JTextBox(12);
        jLabel13 = new javax.swing.JLabel();
        TextIdClient = new controls.JTextBox(12);
        btnAjouter2 = new controls.JMyBottom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 32)); // NOI18N
        jLabel1.setText("Programme");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Numéro :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Destination :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Durée :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        Textduree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextdureeActionPerformed(evt);
            }
        });
        getContentPane().add(Textduree, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        TextId.setEditable(false);
        getContentPane().add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));
        getContentPane().add(Textdestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        getContentPane().add(TextRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Chercher avec :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        RadBtnNum.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnNum.setSelected(true);
        RadBtnNum.setText("Numéro");
        RadBtnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadBtnNumActionPerformed(evt);
            }
        });
        getContentPane().add(RadBtnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        RadBtnDestination.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnDestination.setText("Destination");
        getContentPane().add(RadBtnDestination, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        RadBtnDurée.setBackground(new java.awt.Color(255, 255, 255));
        RadBtnDurée.setText("Durée");
        getContentPane().add(RadBtnDurée, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, -1, -1));

        btnRecherche.setText("Rechercher");
        btnRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercheActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        RdoDate.setBackground(new java.awt.Color(255, 255, 255));
        RdoDate.setText("Date");
        getContentPane().add(RdoDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, -1, -1));

        tblPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Destination", "Date", "Durée", "Prix"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPro);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, 340));

        btnRetoure.setText("Retoure");
        btnRetoure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetoureActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetoure, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        btnTrouver.setText("Trouver");
        btnTrouver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrouverActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrouver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 100, -1));

        btnTout.setText("Tout");
        btnTout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToutActionPerformed(evt);
            }
        });
        getContentPane().add(btnTout, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 280, 90, -1));

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });
        getContentPane().add(btnEffacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 90, -1));

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 100, -1));

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 90, -1));

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 240, 90, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Date :");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));
        getContentPane().add(TextDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 220, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Prix :");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        TextPrix.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TextPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        RdoPrix.setBackground(new java.awt.Color(255, 255, 255));
        RdoPrix.setText("Prix");
        getContentPane().add(RdoPrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Matricule :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        TextMatricule.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TextMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        btnAjouter1.setText("Utiliser une véhicule");
        btnAjouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouter1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Nbr de personnes :");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        TextnbrPers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TextnbrPers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Num client :");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        TextIdClient.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(TextIdClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        btnAjouter2.setText("Réserver");
        btnAjouter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouter2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 127, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadBtnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadBtnNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadBtnNumActionPerformed
    Entity.Programme pro = new Entity.Programme();
    private void btnRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercheActionPerformed
        String cherche ="select * from programme where ";
        if (RadBtnNum.isSelected()){ cherche+="id ="+TextRecherche.getText();}
        else if (RadBtnDestination.isSelected()){ cherche+="destination ='"+TextRecherche.getText()+"'";}
        else if (RadBtnDurée.isSelected()){ cherche+="duree ="+TextRecherche.getText();}
        else if (RdoDate.isSelected()){ cherche+="date ='"+TextRecherche.getText()+"'";}
        else if (RdoPrix.isSelected()){ cherche+="prix ="+TextRecherche.getText();}
        pro.getCustomRows(cherche, tblPro);

    }//GEN-LAST:event_btnRechercheActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        btnGroupPro.add(RadBtnDestination);
        btnGroupPro.add(RadBtnDurée);
        btnGroupPro.add(RadBtnNum);
        btnGroupPro.add(RdoDate);
        btnGroupPro.add(RdoPrix);
        pro.getAllRows(tblPro);
        Clear();
    }//GEN-LAST:event_formWindowOpened

    private void btnToutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToutActionPerformed
        // TODO add your handling code here:
        pro.getAllRows(tblPro);
    }//GEN-LAST:event_btnToutActionPerformed
     
    private void setValues(){
    pro.setId(Integer.parseInt(TextId.getText()));
    pro.setDestination(Textdestination.getText());
    SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
    pro.setDate(String.valueOf(s.format(TextDate.getDate())));
    pro.setDuree(Integer.parseInt(Textduree.getText()));
    pro.setPrix(Double.parseDouble(TextPrix.getText()));
    }
    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // TODO add your handling code here:
        setValues();
    pro.add();
    Clear();
    pro.getAllRows(tblPro);
        
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnRetoureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetoureActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Tools.Tools.OpenForm(new frmMain());
    }//GEN-LAST:event_btnRetoureActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        // TODO add your handling code here:
        setValues();
        pro.update();
        Clear();
        pro.getAllRows(tblPro);
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        // TODO add your handling code here:
        if(Tools.Tools.ConfirmMessage("Voulez vous supprimer ? ")){
       setValues();
       pro.delete();
       Clear();
       pro.getAllRows(tblPro);}
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnTrouverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrouverActionPerformed
        // TODO add your handling code here:
        String strproNo = (String) Tools.Tools.InputBox("Entrer le Numéro de programme");
    int proNo = Integer.parseInt(strproNo);
    pro.setId(proNo);
    pro.getOneRow(tblPro);
    }//GEN-LAST:event_btnTrouverActionPerformed

    private void tblProMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProMouseClicked
        // TODO add your handling code here:
         try{
         int row = tblPro.getSelectedRow();
         String id = tblPro.getValueAt(row, 0).toString();
         String destination = tblPro.getValueAt(row, 1).toString();
         String date = tblPro.getValueAt(row, 2).toString();
         String duree = tblPro.getValueAt(row, 3).toString();
         String prix = tblPro.getValueAt(row, 4).toString();
         TextId.setText(id);
         Textdestination.setText(destination);
         Textduree.setText(duree);
         SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
         Date bd = s.parse(date);
         TextDate.setDate(bd);
         TextPrix.setText(prix);
         btnAjouter.setEnabled(false);
         btnModifier.setEnabled(true);
         btnSupprimer.setEnabled(true);
         }catch(Exception ex)
         {Message(ex.getMessage());} 
    }//GEN-LAST:event_tblProMouseClicked

    private void TextdureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextdureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextdureeActionPerformed
Entity.Voiture_Programme vp =  new Voiture_Programme();
Entity.Voiture v = new Entity.Voiture();
    private void btnAjouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouter1ActionPerformed
        vp.setIdProgramme(Integer.parseInt(TextId.getText()));
        vp.setIdVoiture(TextMatricule.getText());
        vp.add();
        v.location(TextMatricule.getText());
    }//GEN-LAST:event_btnAjouter1ActionPerformed
Entity.Reservation r = new Reservation();
Entity.Client_Numéros cn = new Client_Numéros();
    private void btnAjouter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouter2ActionPerformed
     r.setIdClient(Integer.parseInt(cn.getEmpByPhone(TextIdClient.getText())));
     r.setIdProgramme(Integer.parseInt(TextId.getText()));
     r.setNbrPersonne(Integer.parseInt(TextnbrPers.getText()));
     Double total = Integer.parseInt(TextnbrPers.getText()) * Double.parseDouble(TextPrix.getText());
     r.setTotal(total);
     SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
     r.setDate(String.valueOf(s.format(new Date())));
     r.add();

    }//GEN-LAST:event_btnAjouter2ActionPerformed
    private void Clear(){
    Tools.Tools.ClearTexts(this);
    TextId.setText(pro.getAutoNumber());
    btnAjouter.setEnabled(true);
    btnModifier.setEnabled(false);
    btnSupprimer.setEnabled(false);
    Textdestination.requestFocus();}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadBtnDestination;
    private javax.swing.JRadioButton RadBtnDurée;
    private javax.swing.JRadioButton RadBtnNum;
    private javax.swing.JRadioButton RdoDate;
    private javax.swing.JRadioButton RdoPrix;
    private com.toedter.calendar.JDateChooser TextDate;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextIdClient;
    private javax.swing.JTextField TextMatricule;
    private javax.swing.JTextField TextPrix;
    private javax.swing.JTextField TextRecherche;
    private javax.swing.JTextField Textdestination;
    private javax.swing.JTextField Textduree;
    private javax.swing.JTextField TextnbrPers;
    private controls.JMyBottom btnAjouter;
    private controls.JMyBottom btnAjouter1;
    private controls.JMyBottom btnAjouter2;
    private controls.JMyBottom btnEffacer;
    private javax.swing.ButtonGroup btnGroupPro;
    private controls.JMyBottom btnModifier;
    private controls.JMyBottom btnRecherche;
    private controls.JMyBottom btnRetoure;
    private controls.JMyBottom btnSupprimer;
    private controls.JMyBottom btnTout;
    private controls.JMyBottom btnTrouver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPro;
    // End of variables declaration//GEN-END:variables
}
